#! /usr/bin/env bash

VERSION={{ go_ver }}

golangurl={{go_tgz_url}}
downloaddir="${HOME}/tmp/go-download"
basedir="${HOME}  "
installdir="${basedir}/_${VERSION}"

echo "This script installs Golang into your home folder"

if [ -d "${basedir}/${VERSION}" ]; then
  echo "seems to be installed"
  exit 1
fi

echo "Creating download directory ${downloaddir}"
mkdir -p ${downloaddir}

echo "Downloading Golang"
wget "${golangurl}" -O "${downloaddir}/go.tar.gz"

echo "Extracting Golang distribution"
mkdir -p "${installdir}"
tar -C "${installdir}" -xzf "${downloaddir}/go.tar.gz"
mv "${installdir}/go" "${basedir}/${VERSION}"

echo "Linking current version"
rm "${basedir}/current"
ln -s "${basedir}/${VERSION}" "${basedir}/current"

echo "Removing temporary files/folders"
rm -rf "${installdir}"
rm -rf "${downloaddir}"